#
###################################
# Site wide configuration
####################################
#
title: Wasiq
email: wfmohamm@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://wasiqm.github.io" # the base hostname & protocol for your site
keywords: ["Data Science", "Wasiq", "Waterloo", "Systems Design Engineering", "Software Engineer", "Wasiq Mohammad", "Facebook", "Canadian Space Agency"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Wasiq Mohammad
  avatar: wasiq-logo.png
  job: "4th year Systems Design Engineering student"
  bio: |
        Interested in data, machine learning, and doing cool things with code.
        Previously @ Facebook and the Canadian Space Agency. 
        Graduating from UW soon and looking for my next adventure.
  email: wfmohamm@uwaterloo.ca
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wasiqm #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: wasiqm #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  flickr: #username
  codepen: #username
  telegram: #username
